### ISSUE TITLE
Enable APM for all PHP Versions

### ISSUE THREAD

**Issue by abien** [plesk/ext-new-relic#1]
NR APM should be avilable for Plesk's PHP Versions in the system. This is how we do it on our systems:

```
$#> NR_INSTALL_PHPLIST=/opt/plesk/php/5.2/bin/:/opt/plesk/php/5.3/bin/:/opt/plesk/php/5.4/bin/:/opt/plesk/php/5.5/bin/:/opt/plesk/php/5.6/bin/:/opt/plesk/php/7.0/bin/
$#> export NR_INSTALL_PHPLIST
$#> newrelic-install install 
```

I suggest to beautify above logic before actually implementing this.

- check which php versions are actually present in the system. Only deploy the NR PHP extensions for installed versions. Also make sure this logic keeps working if the list of possible php version changes (ex: PHP7.1)
- maybe even ask the user which versions he wants

**Comment by StoneISStephan** [comment]
You can do all this in a single line ;-)

NR_INSTALL_PHPLIST=/opt/plesk/php/5.2/bin/:/opt/plesk/php/5.3/bin/:/opt/plesk/php/5.4/bin/:/opt/plesk/php/5.5/bin/:/opt/plesk/php/5.6/bin/:/opt/plesk/php/7.0/bin/ newrelic-install install

**Comment by Kubik-Rubik** [comment]
@abien @StoneISStephan Hey guys, thank you for your input. This is already on my To-Do list! :-)

**Comment by Kubik-Rubik** [comment]
Added the best possible variant in 1.0.0-2:

<img width="519" alt="screenshot 2016-12-05 22 39 46" src="https://cloud.githubusercontent.com/assets/1976103/20903504/cfb1a00e-bb3b-11e6-9506-a7bc19728c1c.png">

Please make a _git pull_ or download the zip archive anew.

Cheers

**Comment by Kubik-Rubik** [comment]
Improved the PHP handler recognition in 1.0.0-3 further:

<img width="468" alt="screenshot 2016-12-07 16 57 34" src="https://cloud.githubusercontent.com/assets/1976103/20982520/363715d8-bcb9-11e6-8f3a-4a7d774f035b.png">
