### ISSUE TITLE
CloudLinux Support

### ISSUE THREAD

**Issue by StoneISStephan** [plesk/ext-new-relic#2]
Hi,

currently this extension does not create a working install of New Relic within CloudLinux.

See https://www.lucasrolff.com/cpanel/new-relic-and-cloudlinux/ for more info on the extra steps needed for NR to work in CL.

Not sure if this extension should provide the entire setup, but perhaps some checks to check if everything is done to create a working environment would be nice.

**Comment by Kubik-Rubik** [comment]
Hi @StoneISStephan,

thank you for your input. CloudLinux is not on the list of supported operation systems (yet):

> Supported operation systems: Ubuntu, Debian, CentOs and Red Hat

I would be happy if you could make a pull request to add it to the list!
