### ISSUE TITLE
Issue about Wordpress plugin's updates monitoring

### ISSUE THREAD

**Issue by vbaranovskiy-plesk** [plesk/ext-new-relic#4]
One of the customers reports about an issue with Wordpress plugin's updates monitoring via RELIC using a plesk extension.

STEPS TO REPRODUCE:
1 Install Plesk + Relic extension+ WordPress toolkit
2 Setup relic extension and relic's account to monitoring a WordPress plugins actions 
3 Try to update some plugins via Toolkit

ACTUAL RESULTS:
Error shown as follows.
The WordPress plugins were updated with errors:
Installation "....": open /var/log/newrelic/newrelic-daemon.log: permission denied open /var/log/newrelic/newrelic-daemon.log: permission denied

EXPECTED RESULTS:
Plugins are updates successfully.

ADDITIONAL INFO.
Wordpress plugins are updated successfully without Relic monitoring

KNOWN WORKAROUND:
Change permissions of /var/log/newrelic/newrelic-daemon.log

rw-rr- 1 root root 0 Jan 5 03:42 /var/log/newrelic/newrelic-daemon.log
To
chmod 666 /var/log/newrelic/newrelic-daemon.log

**Comment by Kubik-Rubik** [comment]
Closed. Feel free to reopen if this issue is reported again!

**Comment by alapiere** [comment]
Issue still happening, and breaking all instances in wp-tookit
