### ISSUE TITLE
CentOS 7 Support

### ISSUE THREAD

**Issue by timbutler** [plesk/ext-new-relic#5]
Out of the box, the APM component of the New Relic extension doesn't work on any CentOS 7 / RHEL 7 based system. This has been tested with the latest Plesk Onyx 17.8.11, Update #6.

The issue is that the PHP FPM processes use the PrivateTmp directive for SystemD, which means they get an isolated /tmp mount (which is a good thing!!) and therefore unable to access the default New Relic socket.

The workaround is to edit `/etc/newrelic/newrelic.cfg` to point the socket to a different location (eg /run) and then update all of the newrelic.ini files to also point here. 

Ideally, this should be configured by default during the installation to save manual changes being required.

**Comment by Kubik-Rubik** [comment]
Hello @timbutler, I can confirm the issue. Thank you for reporting it!

I will work on a solution and update the extension asap.

**Comment by Kubik-Rubik** [comment]
Fixed with https://github.com/plesk/ext-new-relic/commit/b9e0c7872d72ec8bf7d7b74a596f0a36d75e52e8
