### ISSUE TITLE
Error during installation on Plesk

### ISSUE THREAD

**Issue by olegburca** [plesk/ext-new-relic#6]
Hi,
I just tried to install NewRelic extension on my Plesk server (Plesk 17.5.3, CloudLinux release 7.5) and got the following error:

> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
> 100 8141 100 8141 0 0 13623 0 --:--:-- --:--:-- --:--:-- 13636
> Config error: File contains no section headers.
> file: file:///etc/yum.repos.d/newrelic-infra.repo, line: 1
> '<html>\n'
> Error:
> Config error: File contains no section headers.
> file: file:///etc/yum.repos.d/newrelic-infra.repo, line: 1
> '<html>\n'

Is there a chanse to get it working with CloudLinux?

**Comment by Kubik-Rubik** [comment]
https://github.com/plesk/ext-new-relic/issues/7
